<a href="https://colab.research.google.com/github/Sahil9424r/med/blob/master/MedicineRecomendationSystem.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [ ]:
df=pd.read_csv('/content/drive/MyDrive/Datasets/Training.csv')

In [ ]:
df.head()

,itching,skin_rash,nodal_skin_eruptions,continuous_sneezing,shivering,chills,joint_pain,stomach_pain,acidity,ulcers_on_tongue,...,blackheads,scurring,skin_peeling,silver_like_dusting,small_dents_in_nails,inflammatory_nails,blister,red_sore_around_nose,yellow_crust_ooze,prognosis
0,1,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection
1,0,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection
2,1,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection
3,1,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection
4,1,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection

In [ ]:
df.shape

(4920, 133)

In [ ]:
len(df.prognosis.unique())

41

so total unique disiease are 41 but total records is of 4920

In [ ]:
df.prognosis.unique()

array(['Fungal infection', 'Allergy', 'GERD', 'Chronic cholestasis',
       'Drug Reaction', 'Peptic ulcer diseae', 'AIDS', 'Diabetes ',
       'Gastroenteritis', 'Bronchial Asthma', 'Hypertension ', 'Migraine',
       'Cervical spondylosis', 'Paralysis (brain hemorrhage)', 'Jaundice',
       'Malaria', 'Chicken pox', 'Dengue', 'Typhoid', 'hepatitis A',
       'Hepatitis B', 'Hepatitis C', 'Hepatitis D', 'Hepatitis E',
       'Alcoholic hepatitis', 'Tuberculosis', 'Common Cold', 'Pneumonia',
       'Dimorphic hemmorhoids(piles)', 'Heart attack', 'Varicose veins',
       'Hypothyroidism', 'Hyperthyroidism', 'Hypoglycemia',
       'Osteoarthristis', 'Arthritis',
       '(vertigo) Paroymsal  Positional Vertigo', 'Acne',
       'Urinary tract infection', 'Psoriasis', 'Impetigo'], dtype=object)

In [ ]:
df.isnull().sum().sum()

np.int64(0)

so no null values

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4920 entries, 0 to 4919
Columns: 133 entries, itching to prognosis
dtypes: int64(132), object(1)
memory usage: 5.0+ MB

In [ ]:
df.duplicated().sum()

np.int64(4616)

so there are many duplicates as seen

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,LabelEncoder,OneHotEncoder,OrdinalEncoder
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [ ]:
df.head()

,itching,skin_rash,nodal_skin_eruptions,continuous_sneezing,shivering,chills,joint_pain,stomach_pain,acidity,ulcers_on_tongue,...,blackheads,scurring,skin_peeling,silver_like_dusting,small_dents_in_nails,inflammatory_nails,blister,red_sore_around_nose,yellow_crust_ooze,prognosis
0,1,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection
1,0,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection
2,1,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection
3,1,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection
4,1,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection

In [ ]:
x=df.drop('prognosis',axis=1)
y=df['prognosis']

In [ ]:
x.head()

,itching,skin_rash,nodal_skin_eruptions,continuous_sneezing,shivering,chills,joint_pain,stomach_pain,acidity,ulcers_on_tongue,...,pus_filled_pimples,blackheads,scurring,skin_peeling,silver_like_dusting,small_dents_in_nails,inflammatory_nails,blister,red_sore_around_nose,yellow_crust_ooze
0,1,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,1,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,1,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
le=LabelEncoder()
y=le.fit_transform(y)

In [ ]:
y.min()

np.int64(0)

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=42)

In [ ]:
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((3444, 132), (1476, 132), (3444,), (1476,))

train model

In [ ]:

from sklearn.ensemble import RandomForestClassifier,GradientBoostingClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import MultinomialNB

In [ ]:
models = {
    "Random Forest": RandomForestClassifier(n_estimators=100,random_state=42),
    "Gradient Boosting": GradientBoostingClassifier(n_estimators=100,random_state=42),
    "KNN": KNeighborsClassifier(n_neighbors=5),
    "SVM": SVC(kernel='linear'),
    "Multinomial Naive Bayes": MultinomialNB()
}



trained_models = {}
for name, model in models.items():
    model.fit(x_train, y_train)
    y_pred = model.predict(x_test)
    accuracy = accuracy_score(y_test, y_pred)
    print(f"{name} Accuracy: {accuracy}")
    print(f"{name},classification_report:{classification_report(y_test, y_pred)}")
    print(f"{name},confusion_matrix:{confusion_matrix(y_test, y_pred)}")
    trained_models[name] = model
    print(np.array2string(y_pred, separator=','))
    print(f"{name} trained successfully!")

Random Forest Accuracy: 1.0
Random Forest,classification_report:              precision    recall  f1-score   support

           0       1.00      1.00      1.00        32
           1       1.00      1.00      1.00        39
           2       1.00      1.00      1.00        41
           3       1.00      1.00      1.00        36
           4       1.00      1.00      1.00        35
           5       1.00      1.00      1.00        36
           6       1.00      1.00      1.00        44
           7       1.00      1.00      1.00        32
           8       1.00      1.00      1.00        35
           9       1.00      1.00      1.00        30
          10       1.00      1.00      1.00        31
          11       1.00      1.00      1.00        40
          12       1.00      1.00      1.00        33
          13       1.00      1.00      1.00        45
          14       1.00      1.00      1.00        35
          15       1.00      1.00      1.00        28
          16       1.00      1.00      1.00        41
          17       1.00      1.00      1.00        40
          18       1.00      1.00      1.00        36
          19       1.00      1.00      1.00        46
          20       1.00      1.00      1.00        40
          21       1.00      1.00      1.00        35
          22       1.00      1.00      1.00        47
          23       1.00      1.00      1.00        31
          24       1.00      1.00      1.00        37
          25       1.00      1.00      1.00        42
          26       1.00      1.00      1.00        33
          27       1.00      1.00      1.00        35
          28       1.00      1.00      1.00        34
          29       1.00      1.00      1.00        30
          30       1.00      1.00      1.00        36
          31       1.00      1.00      1.00        28
          32       1.00      1.00      1.00        34
          33       1.00      1.00      1.00        27
          34       1.00      1.00      1.00        39
          35       1.00      1.00      1.00        32
          36       1.00      1.00      1.00        35
          37       1.00      1.00      1.00        34
          38       1.00      1.00      1.00        36
          39       1.00      1.00      1.00        37
          40       1.00      1.00      1.00        39

    accuracy                           1.00      1476
   macro avg       1.00      1.00      1.00      1476
weighted avg       1.00      1.00      1.00      1476

Random Forest,confusion_matrix:[[32  0  0 ...  0  0  0]
 [ 0 39  0 ...  0  0  0]
 [ 0  0 41 ...  0  0  0]
 ...
 [ 0  0  0 ... 36  0  0]
 [ 0  0  0 ...  0 37  0]
 [ 0  0  0 ...  0  0 39]]
[ 2, 2,24,...,30,26,11]
Random Forest trained successfully!
Gradient Boosting Accuracy: 1.0
Gradient Boosting,classification_report:              precision    recall  f1-score   support

           0       1.00      1.00      1.00        32
           1       1.00      1.00      1.00        39
           2       1.00      1.00      1.00        41
           3       1.00      1.00      1.00        36
           4       1.00      1.00      1.00        35
           5       1.00      1.00      1.00        36
           6       1.00      1.00      1.00        44
           7       1.00      1.00      1.00        32
           8       1.00      1.00      1.00        35
           9       1.00      1.00      1.00        30
          10       1.00      1.00      1.00        31
          11       1.00      1.00      1.00        40
          12       1.00      1.00      1.00        33
          13       1.00      1.00      1.00        45
          14       1.00      1.00      1.00        35
          15       1.00      1.00      1.00        28
          16       1.00      1.00      1.00        41
          17       1.00      1.00      1.00        40
          18       1.00      1.00      1.00        36
          19       1.00      1.00      1.00        46
          20       1.00      1.00      1.00        40
          21       1.00      1.00      1.00        35
          22       1.00      1.00      1.00        47
          23       1.00      1.00      1.00        31
          24       1.00      1.00      1.00        37
          25       1.00      1.00      1.00        42
          26       1.00      1.00      1.00        33
          27       1.00      1.00      1.00        35
          28       1.00      1.00      1.00        34
          29       1.00      1.00      1.00        30
          30       1.00      1.00      1.00        36
          31       1.00      1.00      1.00        28
          32       1.00      1.00      1.00        34
          33       1.00      1.00      1.00        27
          34       1.00      1.00      1.00        39
          35       1.00      1.00      1.00        32
          36       1.00      1.00      1.00        35
          37       1.00      1.00      1.00        34
          38       1.00      1.00      1.00        36
          39       1.00      1.00      1.00        37
          40       1.00      1.00      1.00        39

    accuracy                           1.00      1476
   macro avg       1.00      1.00      1.00      1476
weighted avg       1.00      1.00      1.00      1476

Gradient Boosting,confusion_matrix:[[32  0  0 ...  0  0  0]
 [ 0 39  0 ...  0  0  0]
 [ 0  0 41 ...  0  0  0]
 ...
 [ 0  0  0 ... 36  0  0]
 [ 0  0  0 ...  0 37  0]
 [ 0  0  0 ...  0  0 39]]
[ 2, 2,24,...,30,26,11]
Gradient Boosting trained successfully!
KNN Accuracy: 1.0
KNN,classification_report:              precision    recall  f1-score   support

           0       1.00      1.00      1.00        32
           1       1.00      1.00      1.00        39
           2       1.00      1.00      1.00        41
           3       1.00      1.00      1.00        36
           4       1.00      1.00      1.00        35
           5       1.00      1.00      1.00        36
           6       1.00      1.00      1.00        44
           7       1.00      1.00      1.00        32
           8       1.00      1.00      1.00        35
           9       1.00      1.00      1.00        30
          10       1.00      1.00      1.00        31
          11       1.00      1.00      1.00        40
          12       1.00      1.00      1.00        33
          13       1.00      1.00      1.00        45
          14       1.00      1.00      1.00        35
          15       1.00      1.00      1.00        28
          16       1.00      1.00      1.00        41
          17       1.00      1.00      1.00        40
          18       1.00      1.00      1.00        36
          19       1.00      1.00      1.00        46
          20       1.00      1.00      1.00        40
          21       1.00      1.00      1.00        35
          22       1.00      1.00      1.00        47
          23       1.00      1.00      1.00        31
          24       1.00      1.00      1.00        37
          25       1.00      1.00      1.00        42
          26       1.00      1.00      1.00        33
          27       1.00      1.00      1.00        35
          28       1.00      1.00      1.00        34
          29       1.00      1.00      1.00        30
          30       1.00      1.00      1.00        36
          31       1.00      1.00      1.00        28
          32       1.00      1.00      1.00        34
          33       1.00      1.00      1.00        27
          34       1.00      1.00      1.00        39
          35       1.00      1.00      1.00        32
          36       1.00      1.00      1.00        35
          37       1.00      1.00      1.00        34
          38       1.00      1.00      1.00        36
          39       1.00      1.00      1.00        37
          40       1.00      1.00      1.00        39

    accuracy                           1.00      1476
   macro avg       1.00      1.00      1.00      1476
weighted avg       1.00      1.00      1.00      1476

KNN,confusion_matrix:[[32  0  0 ...  0  0  0]
 [ 0 39  0 ...  0  0  0]
 [ 0  0 41 ...  0  0  0]
 ...
 [ 0  0  0 ... 36  0  0]
 [ 0  0  0 ...  0 37  0]
 [ 0  0  0 ...  0  0 39]]
[ 2, 2,24,...,30,26,11]
KNN trained successfully!
SVM Accuracy: 1.0
SVM,classification_report:              precision    recall  f1-score   support

           0       1.00      1.00      1.00        32
           1       1.00      1.00      1.00        39
           2       1.00      1.00      1.00        41
           3       1.00      1.00      1.00        36
           4       1.00      1.00      1.00        35
           5       1.00      1.00      1.00        36
           6       1.00      1.00      1.00        44
           7       1.00      1.00      1.00        32
           8       1.00      1.00      1.00        35
           9       1.00      1.00      1.00        30
          10       1.00      1.00      1.00        31
          11       1.00      1.00      1.00        40
          12       1.00      1.00      1.00        33
          13       1.00      1.00      1.00        45
          14       1.00      1.00      1.00        35
          15       1.00      1.00      1.00        28
          16       1.00      1.00      1.00        41
          17       1.00      1.00      1.00        40
          18       1.00      1.00      1.00        36
          19       1.00      1.00      1.00        46
          20       1.00      1.00      1.00        40
          21       1.00      1.00      1.00        35
          22       1.00      1.00      1.00        47
          23       1.00      1.00      1.00        31
          24       1.00      1.00      1.00        37
          25       1.00      1.00      1.00        42
          26       1.00      1.00      1.00        33
          27       1.00      1.00      1.00        35
          28       1.00      1.00      1.00        34
          29       1.00      1.00      1.00        30
          30       1.00      1.00      1.00        36
          31       1.00      1.00      1.00        28
          32       1.00      1.00      1.00        34
          33       1.00      1.00      1.00        27
          34       1.00      1.00      1.00        39
          35       1.00      1.00      1.00        32
          36       1.00      1.00      1.00        35
          37       1.00      1.00      1.00        34
          38       1.00      1.00      1.00        36
          39       1.00      1.00      1.00        37
          40       1.00      1.00      1.00        39

    accuracy                           1.00      1476
   macro avg       1.00      1.00      1.00      1476
weighted avg       1.00      1.00      1.00      1476

SVM,confusion_matrix:[[32  0  0 ...  0  0  0]
 [ 0 39  0 ...  0  0  0]
 [ 0  0 41 ...  0  0  0]
 ...
 [ 0  0  0 ... 36  0  0]
 [ 0  0  0 ...  0 37  0]
 [ 0  0  0 ...  0  0 39]]
[ 2, 2,24,...,30,26,11]
SVM trained successfully!
Multinomial Naive Bayes Accuracy: 1.0
Multinomial Naive Bayes,classification_report:              precision    recall  f1-score   support

           0       1.00      1.00      1.00        32
           1       1.00      1.00      1.00        39
           2       1.00      1.00      1.00        41
           3       1.00      1.00      1.00        36
           4       1.00      1.00      1.00        35
           5       1.00      1.00      1.00        36
           6       1.00      1.00      1.00        44
           7       1.00      1.00      1.00        32
           8       1.00      1.00      1.00        35
           9       1.00      1.00      1.00        30
          10       1.00      1.00      1.00        31
          11       1.00      1.00      1.00        40
          12       1.00      1.00      1.00        33
          13       1.00      1.00      1.00        45
          14       1.00      1.00      1.00        35
          15       1.00      1.00      1.00        28
          16       1.00      1.00      1.00        41
          17       1.00      1.00      1.00        40
          18       1.00      1.00      1.00        36
          19       1.00      1.00      1.00        46
          20       1.00      1.00      1.00        40
          21       1.00      1.00      1.00        35
          22       1.00      1.00      1.00        47
          23       1.00      1.00      1.00        31
          24       1.00      1.00      1.00        37
          25       1.00      1.00      1.00        42
          26       1.00      1.00      1.00        33
          27       1.00      1.00      1.00        35
          28       1.00      1.00      1.00        34
          29       1.00      1.00      1.00        30
          30       1.00      1.00      1.00        36
          31       1.00      1.00      1.00        28
          32       1.00      1.00      1.00        34
          33       1.00      1.00      1.00        27
          34       1.00      1.00      1.00        39
          35       1.00      1.00      1.00        32
          36       1.00      1.00      1.00        35
          37       1.00      1.00      1.00        34
          38       1.00      1.00      1.00        36
          39       1.00      1.00      1.00        37
          40       1.00      1.00      1.00        39

    accuracy                           1.00      1476
   macro avg       1.00      1.00      1.00      1476
weighted avg       1.00      1.00      1.00      1476

Multinomial Naive Bayes,confusion_matrix:[[32  0  0 ...  0  0  0]
 [ 0 39  0 ...  0  0  0]
 [ 0  0 41 ...  0  0  0]
 ...
 [ 0  0  0 ... 36  0  0]
 [ 0  0  0 ...  0 37  0]
 [ 0  0  0 ...  0  0 39]]
[ 2, 2,24,...,30,26,11]
Multinomial Naive Bayes trained successfully!

as all are giving 100% accuracy so let take any of them

In [ ]:
trained_models["SVM"]

SVC(kernel='linear')

In [ ]:
import pickle
pickle.dump(trained_models["SVM"],open('/content/drive/MyDrive/model/svc.pkl','wb'))

In [ ]:
svc=pickle.load(open('/content/drive/MyDrive/model/svc.pkl','rb'))

In [ ]:
svc

SVC(kernel='linear')

In [ ]:
x_test.iloc[0]

itching                 0
skin_rash               1
nodal_skin_eruptions    0
continuous_sneezing     0
shivering               0
                       ..
small_dents_in_nails    0
inflammatory_nails      0
blister                 0
red_sore_around_nose    0
yellow_crust_ooze       0
Name: 373, Length: 132, dtype: int64

In [ ]:
v=0;
t=x_test.iloc[v].values.reshape(1,-1)
print("Predicted label",svc.predict(t)[0])
print("Actual Label",y_test[v])

Predicted label 2
Actual Label 2

In [ ]:
v=10;
t=x_test.iloc[v].values.reshape(1,-1)
print("Predicted label",svc.predict(t)[0])
print("Actual Label",y_test[v])

Predicted label 38
Actual Label 38

so both prediction and original match

In [ ]:
sym_des=pd.read_csv('/content/drive/MyDrive/Datasets/symtoms_df.csv')
precautions=pd.read_csv('/content/drive/MyDrive/Datasets/precautions_df.csv')
workout=pd.read_csv('/content/drive/MyDrive/Datasets/workout_df.csv')
description=pd.read_csv('/content/drive/MyDrive/Datasets/description.csv')
diets=pd.read_csv('/content/drive/MyDrive/Datasets/diets.csv')
medication=pd.read_csv('/content/drive/MyDrive/Datasets/medications.csv')

In [ ]:
sym_des.head()

,Unnamed: 0,Disease,Symptom_1,Symptom_2,Symptom_3,Symptom_4
0,0,Fungal infection,itching,skin_rash,nodal_skin_eruptions,dischromic _patches
1,1,Fungal infection,skin_rash,nodal_skin_eruptions,dischromic _patches,NaN
2,2,Fungal infection,itching,nodal_skin_eruptions,dischromic _patches,NaN
3,3,Fungal infection,itching,skin_rash,dischromic _patches,NaN
4,4,Fungal infection,itching,skin_rash,nodal_skin_eruptions,NaN

In [ ]:
precautions.head()

,Unnamed: 0,Disease,Precaution_1,Precaution_2,Precaution_3,Precaution_4
0,0,Drug Reaction,stop irritation,consult nearest hospital,stop taking drug,follow up
1,1,Malaria,Consult nearest hospital,avoid oily food,avoid non veg food,keep mosquitos out
2,2,Allergy,apply calamine,cover area with bandage,NaN,use ice to compress itching
3,3,Hypothyroidism,reduce stress,exercise,eat healthy,get proper sleep
4,4,Psoriasis,wash hands with warm soapy water,stop bleeding using pressure,consult doctor,salt baths

In [ ]:
workout.head()

   Unnamed: 0.1  Unnamed: 0           disease                    workout
0             0           0  Fungal infection         Avoid sugary foods
1             1           1  Fungal infection         Consume probiotics
2             2           2  Fungal infection  Increase intake of garlic
3             3           3  Fungal infection     Include yogurt in diet
4             4           4  Fungal infection      Limit processed foods

In [ ]:
description.head()

               Disease                                        Description
0     Fungal infection  Fungal infection is a common skin condition ca...
1              Allergy  Allergy is an immune system reaction to a subs...
2                 GERD  GERD (Gastroesophageal Reflux Disease) is a di...
3  Chronic cholestasis  Chronic cholestasis is a condition where bile ...
4        Drug Reaction  Drug Reaction occurs when the body reacts adve...

In [ ]:
diets.head()

               Disease                                               Diet
0     Fungal infection  ['Antifungal Diet', 'Probiotics', 'Garlic', 'C...
1              Allergy  ['Elimination Diet', 'Omega-3-rich foods', 'Vi...
2                 GERD  ['Low-Acid Diet', 'Fiber-rich foods', 'Ginger'...
3  Chronic cholestasis  ['Low-Fat Diet', 'High-Fiber Diet', 'Lean prot...
4        Drug Reaction  ['Antihistamine Diet', 'Omega-3-rich foods', '...

In [ ]:
medication.head()

               Disease                                         Medication
0     Fungal infection  ['Antifungal Cream', 'Fluconazole', 'Terbinafi...
1              Allergy  ['Antihistamines', 'Decongestants', 'Epinephri...
2                 GERD  ['Proton Pump Inhibitors (PPIs)', 'H2 Blockers...
3  Chronic cholestasis  ['Ursodeoxycholic acid', 'Cholestyramine', 'Me...
4        Drug Reaction  ['Antihistamines', 'Epinephrine', 'Corticoster...

In [ ]:
symptoms_dict = {'itching': 0, 'skin_rash': 1, 'nodal_skin_eruptions': 2, 'continuous_sneezing': 3, 'shivering': 4, 'chills': 5, 'joint_pain': 6, 'stomach_pain': 7, 'acidity': 8, 'ulcers_on_tongue': 9, 'muscle_wasting': 10, 'vomiting': 11, 'burning_micturition': 12, 'spotting_ urination': 13, 'fatigue': 14, 'weight_gain': 15, 'anxiety': 16, 'cold_hands_and_feets': 17, 'mood_swings': 18, 'weight_loss': 19, 'restlessness': 20, 'lethargy': 21, 'patches_in_throat': 22, 'irregular_sugar_level': 23, 'cough': 24, 'high_fever': 25, 'sunken_eyes': 26, 'breathlessness': 27, 'sweating': 28, 'dehydration': 29, 'indigestion': 30, 'headache': 31, 'yellowish_skin': 32, 'dark_urine': 33, 'nausea': 34, 'loss_of_appetite': 35, 'pain_behind_the_eyes': 36, 'back_pain': 37, 'constipation': 38, 'abdominal_pain': 39, 'diarrhoea': 40, 'mild_fever': 41, 'yellow_urine': 42, 'yellowing_of_eyes': 43, 'acute_liver_failure': 44, 'fluid_overload': 45, 'swelling_of_stomach': 46, 'swelled_lymph_nodes': 47, 'malaise': 48, 'blurred_and_distorted_vision': 49, 'phlegm': 50, 'throat_irritation': 51, 'redness_of_eyes': 52, 'sinus_pressure': 53, 'runny_nose': 54, 'congestion': 55, 'chest_pain': 56, 'weakness_in_limbs': 57, 'fast_heart_rate': 58, 'pain_during_bowel_movements': 59, 'pain_in_anal_region': 60, 'bloody_stool': 61, 'irritation_in_anus': 62, 'neck_pain': 63, 'dizziness': 64, 'cramps': 65, 'bruising': 66, 'obesity': 67, 'swollen_legs': 68, 'swollen_blood_vessels': 69, 'puffy_face_and_eyes': 70, 'enlarged_thyroid': 71, 'brittle_nails': 72, 'swollen_extremeties': 73, 'excessive_hunger': 74, 'extra_marital_contacts': 75, 'drying_and_tingling_lips': 76, 'slurred_speech': 77, 'knee_pain': 78, 'hip_joint_pain': 79, 'muscle_weakness': 80, 'stiff_neck': 81, 'swelling_joints': 82, 'movement_stiffness': 83, 'spinning_movements': 84, 'loss_of_balance': 85, 'unsteadiness': 86, 'weakness_of_one_body_side': 87, 'loss_of_smell': 88, 'bladder_discomfort': 89, 'foul_smell_of urine': 90, 'continuous_feel_of_urine': 91, 'passage_of_gases': 92, 'internal_itching': 93, 'toxic_look_(typhos)': 94, 'depression': 95, 'irritability': 96, 'muscle_pain': 97, 'altered_sensorium': 98, 'red_spots_over_body': 99, 'belly_pain': 100, 'abnormal_menstruation': 101, 'dischromic _patches': 102, 'watering_from_eyes': 103, 'increased_appetite': 104, 'polyuria': 105, 'family_history': 106, 'mucoid_sputum': 107, 'rusty_sputum': 108, 'lack_of_concentration': 109, 'visual_disturbances': 110, 'receiving_blood_transfusion': 111, 'receiving_unsterile_injections': 112, 'coma': 113, 'stomach_bleeding': 114, 'distention_of_abdomen': 115, 'history_of_alcohol_consumption': 116, 'fluid_overload.1': 117, 'blood_in_sputum': 118, 'prominent_veins_on_calf': 119, 'palpitations': 120, 'painful_walking': 121, 'pus_filled_pimples': 122, 'blackheads': 123, 'scurring': 124, 'skin_peeling': 125, 'silver_like_dusting': 126, 'small_dents_in_nails': 127, 'inflammatory_nails': 128, 'blister': 129, 'red_sore_around_nose': 130, 'yellow_crust_ooze': 131}
diseases_list = {15: 'Fungal infection', 4: 'Allergy', 16: 'GERD', 9: 'Chronic cholestasis', 14: 'Drug Reaction', 33: 'Peptic ulcer diseae', 1: 'AIDS', 12: 'Diabetes ', 17: 'Gastroenteritis', 6: 'Bronchial Asthma', 23: 'Hypertension ', 30: 'Migraine', 7: 'Cervical spondylosis', 32: 'Paralysis (brain hemorrhage)', 28: 'Jaundice', 29: 'Malaria', 8: 'Chicken pox', 11: 'Dengue', 37: 'Typhoid', 40: 'hepatitis A', 19: 'Hepatitis B', 20: 'Hepatitis C', 21: 'Hepatitis D', 22: 'Hepatitis E', 3: 'Alcoholic hepatitis', 36: 'Tuberculosis', 10: 'Common Cold', 34: 'Pneumonia', 13: 'Dimorphic hemmorhoids(piles)', 18: 'Heart attack', 39: 'Varicose veins', 26: 'Hypothyroidism', 24: 'Hyperthyroidism', 25: 'Hypoglycemia', 31: 'Osteoarthristis', 5: 'Arthritis', 0: '(vertigo) Paroymsal  Positional Vertigo', 2: 'Acne', 38: 'Urinary tract infection', 35: 'Psoriasis', 27: 'Impetigo'}

In [ ]:
def get_predicted_value(symptoms):
    input_vector=np.zeros(len(symptoms_dict))
    for item in symptoms:
      input_vector[symptoms_dict[item]]=1
    return diseases_list[svc.predict([input_vector])[0]]

In [ ]:
def helper(disease):
  descr=description[description['Disease']==disease]['Description'].values[0]
  prec=precautions[precautions['Disease']==disease][['Precaution_1','Precaution_2','Precaution_3','Precaution_4']].values[0]
  med=medication[medication['Disease']==disease]['Medication'].values[0]
  di=diets[diets['Disease']==disease]['Diet'].values[0]
  work=workout[workout['disease']==disease]['workout'].values
  return descr,prec,med,work,di

In [ ]:
symtoms=input("enter your symptoms:")
user_symptoms=[s for s in symtoms.split(',')]
#ye line likho or not
user_symptoms=[sym.strip("[]") for sym in user_symptoms]
predicted_disease=get_predicted_value(user_symptoms)
descr,prec,med,work,di=helper('Malaria')

print("=============Predicted Disease===========")
print(predicted_disease)
print("=============Description==================")
print(descr)
print("=============Precaution==================")
for i in range(4):
  print(f"{i}:{prec[i]}")

print("=============Medication==================")
print(med)

print("=============Diet==================")
print(di)

print("=============Workout==================")
# print(work)
i=1
for w_i in work:
    print(i, ": ", w_i)
    i += 1

# itching,skin_rash

enter your symptoms:itching,skin_rash
=============Predicted Disease===========
Fungal infection
=============Description==================
Malaria is a mosquito-borne infectious disease affecting humans and other animals.
=============Precaution==================
0:Consult nearest hospital
1:avoid oily food
2:avoid non veg food
3:keep mosquitos out
=============Medication==================
['Antimalarial drugs', 'Antipyretics', 'Antiemetic drugs', 'IV fluids', 'Blood transfusions']
=============Diet==================
['Malaria Diet', 'Hydration', 'High-Calorie Diet', 'Soft and bland foods', 'Oral rehydration solutions']
=============Workout==================
1 :  Stay hydrated
2 :  Consume nutrient-rich foods
3 :  Include protein-rich foods
4 :  Consume foods rich in antioxidants
5 :  Limit fatty and greasy foods
6 :  Avoid alcohol and caffeine
7 :  Include vitamin C-rich foods
8 :  Consult a healthcare professional
9 :  Rest and conserve energy
10 :  Gradually resume normal diet

In [ ]:
import sklearn
print(sklearn.__version__)

1.6.1

In [ ]:
import pickle


# Load the pickled model
with open('svc.pkl', 'rb') as file:
    model = pickle.load(file)
print(type(model))

<class 'sklearn.svm._classes.SVC'>

In [ ]:
import sklearn
import numpy
import joblib
import pandas
print("scikit-learn:", sklearn.__version__)
print("numpy:", numpy.__version__)
print("joblib:", joblib.__version__)
print("panda:", pandas.__version__)

scikit-learn: 1.6.1
numpy: 2.0.2
joblib: 1.4.2
panda: 2.2.2

In [ ]:
print(model.__module__)  # To see where it came from
print(model.get_params())  # To get hyperparameters

sklearn.svm._classes
{'C': 1.0, 'break_ties': False, 'cache_size': 200, 'class_weight': None, 'coef0': 0.0, 'decision_function_shape': 'ovr', 'degree': 3, 'gamma': 'scale', 'kernel': 'linear', 'max_iter': -1, 'probability': False, 'random_state': None, 'shrinking': True, 'tol': 0.001, 'verbose': False}

In [ ]:
for attr in dir(model):
    if "version" in attr.lower():
        print(attr, ":", getattr(model, attr))

SVC(kernel='linear')